// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -->Single Auto Tag.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Tags.getAutoTag({
 *     name: "Example",
 * });
 * ```
 */
export function getAutoTag(args: GetAutoTagArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoTagResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTag:getAutoTag", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getAutoTag.
 */
export interface GetAutoTagArgs {
    /**
     * Auto Tag name.
     */
    name: string;
}

/**
 * A collection of values returned by getAutoTag.
 */
export interface GetAutoTagResult {
    /**
     * Auto Tag ID.
     */
    readonly id: number;
    /**
     * Auto Tag name.
     */
    readonly name: string;
    /**
     * Remove tags automatically flag.
     */
    readonly removeTagsAutomatically: boolean;
    /**
     * Specifications.
     */
    readonly specifications: outputs.Tags.GetAutoTagSpecification[];
    /**
     * List of associated tags.
     */
    readonly tags: number[];
}
/**
 * <!-- subcategory:Tags -->Single Auto Tag.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Tags.getAutoTag({
 *     name: "Example",
 * });
 * ```
 */
export function getAutoTagOutput(args: GetAutoTagOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAutoTagResult> {
    return pulumi.output(args).apply((a: any) => getAutoTag(a, opts))
}

/**
 * A collection of arguments for invoking getAutoTag.
 */
export interface GetAutoTagOutputArgs {
    /**
     * Auto Tag name.
     */
    name: pulumi.Input<string>;
}
