// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -> Auto Tag Condition Genres data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionGenres(args: GetAutoTagConditionGenresArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoTagConditionGenresResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTagConditionGenres:getAutoTagConditionGenres", {
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getAutoTagConditionGenres.
 */
export interface GetAutoTagConditionGenresArgs {
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Genres. Space separated list of genres.
     */
    value: string;
}

/**
 * A collection of values returned by getAutoTagConditionGenres.
 */
export interface GetAutoTagConditionGenresResult {
    /**
     * Auto tag condition series type ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Genres. Space separated list of genres.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Tags -> Auto Tag Condition Genres data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionGenresOutput(args: GetAutoTagConditionGenresOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAutoTagConditionGenresResult> {
    return pulumi.output(args).apply((a: any) => getAutoTagConditionGenres(a, opts))
}

/**
 * A collection of arguments for invoking getAutoTagConditionGenres.
 */
export interface GetAutoTagConditionGenresOutputArgs {
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Genres. Space separated list of genres.
     */
    value: pulumi.Input<string>;
}
