// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -> Generic Auto Tag Condition data source. When possible use a specific data source instead.
 * For more information refer to [ Format Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 *  To be used in conjunction with  Format.
 */
export function getAutoTagCondition(args: GetAutoTagConditionArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoTagConditionResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTagCondition:getAutoTagCondition", {
        "implementation": args.implementation,
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getAutoTagCondition.
 */
export interface GetAutoTagConditionArgs {
    /**
     * Implementation.
     */
    implementation: string;
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Value.
     */
    value?: string;
}

/**
 * A collection of values returned by getAutoTagCondition.
 */
export interface GetAutoTagConditionResult {
    /**
     * format condition ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Value.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Tags -> Generic Auto Tag Condition data source. When possible use a specific data source instead.
 * For more information refer to [ Format Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 *  To be used in conjunction with  Format.
 */
export function getAutoTagConditionOutput(args: GetAutoTagConditionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAutoTagConditionResult> {
    return pulumi.output(args).apply((a: any) => getAutoTagCondition(a, opts))
}

/**
 * A collection of arguments for invoking getAutoTagCondition.
 */
export interface GetAutoTagConditionOutputArgs {
    /**
     * Implementation.
     */
    implementation: pulumi.Input<string>;
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Value.
     */
    value?: pulumi.Input<string>;
}
