// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -->List all available Auto Tags.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Tags.getAutoTags({});
 * ```
 */
export function getAutoTags(opts?: pulumi.InvokeOptions): Promise<GetAutoTagsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTags:getAutoTags", {
    }, opts);
}

/**
 * A collection of values returned by getAutoTags.
 */
export interface GetAutoTagsResult {
    /**
     * Auto Tag list.
     */
    readonly autoTags: outputs.Tags.GetAutoTagsAutoTag[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
