// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -> Auto Tag Condition Series Type data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionSeriesType(args: GetAutoTagConditionSeriesTypeArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoTagConditionSeriesTypeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTagConditionSeriesType:getAutoTagConditionSeriesType", {
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getAutoTagConditionSeriesType.
 */
export interface GetAutoTagConditionSeriesTypeArgs {
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Series type. `0` Standard, `1` Daily, `2` Anime.
     */
    value: string;
}

/**
 * A collection of values returned by getAutoTagConditionSeriesType.
 */
export interface GetAutoTagConditionSeriesTypeResult {
    /**
     * Auto tag condition series type ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Series type. `0` Standard, `1` Daily, `2` Anime.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Tags -> Auto Tag Condition Series Type data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionSeriesTypeOutput(args: GetAutoTagConditionSeriesTypeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAutoTagConditionSeriesTypeResult> {
    return pulumi.output(args).apply((a: any) => getAutoTagConditionSeriesType(a, opts))
}

/**
 * A collection of arguments for invoking getAutoTagConditionSeriesType.
 */
export interface GetAutoTagConditionSeriesTypeOutputArgs {
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Series type. `0` Standard, `1` Daily, `2` Anime.
     */
    value: pulumi.Input<string>;
}
