// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Tags -> Auto Tag Condition Root Folder data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionRootFolder(args: GetAutoTagConditionRootFolderArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoTagConditionRootFolderResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getAutoTagConditionRootFolder:getAutoTagConditionRootFolder", {
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getAutoTagConditionRootFolder.
 */
export interface GetAutoTagConditionRootFolderArgs {
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Root folder path.
     */
    value: string;
}

/**
 * A collection of values returned by getAutoTagConditionRootFolder.
 */
export interface GetAutoTagConditionRootFolderResult {
    /**
     * Auto tag condition root folder ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Root folder path.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Tags -> Auto Tag Condition Root Folder data source.
 * For more intagion refer to [Auto Tag Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 */
export function getAutoTagConditionRootFolderOutput(args: GetAutoTagConditionRootFolderOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAutoTagConditionRootFolderResult> {
    return pulumi.output(args).apply((a: any) => getAutoTagConditionRootFolder(a, opts))
}

/**
 * A collection of arguments for invoking getAutoTagConditionRootFolder.
 */
export interface GetAutoTagConditionRootFolderOutputArgs {
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Root folder path.
     */
    value: pulumi.Input<string>;
}
