// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Status -->System Status resource. User must have rights to read `config.xml`.
 * For more information refer to [System Status](https://wiki.servarr.com/sonarr/system#status) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Tags.getSystemStatus({});
 * ```
 */
export function getSystemStatus(opts?: pulumi.InvokeOptions): Promise<GetSystemStatusResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Tags/getSystemStatus:getSystemStatus", {
    }, opts);
}

/**
 * A collection of values returned by getSystemStatus.
 */
export interface GetSystemStatusResult {
    /**
     * App data folder.
     */
    readonly appData: string;
    /**
     * Authentication.
     */
    readonly authentication: string;
    /**
     * Branch.
     */
    readonly branch: string;
    /**
     * Build time.
     */
    readonly buildTime: string;
    /**
     * Delay Profile ID.
     */
    readonly id: number;
    /**
     * Is admin flag.
     */
    readonly isAdmin: boolean;
    /**
     * Is debug flag.
     */
    readonly isDebug: boolean;
    /**
     * Is linux flag.
     */
    readonly isLinux: boolean;
    /**
     * Is osx flag.
     */
    readonly isOsx: boolean;
    /**
     * Is production flag.
     */
    readonly isProduction: boolean;
    /**
     * Is user interactive flag.
     */
    readonly isUserInteractive: boolean;
    /**
     * Is windows flag.
     */
    readonly isWindows: boolean;
    /**
     * Mode.
     */
    readonly mode: string;
    /**
     * OS name.
     */
    readonly osName: string;
    /**
     * OS version.
     */
    readonly osVersion: string;
    /**
     * Package author.
     */
    readonly packageAuthor: string;
    /**
     * Package update mechanism.
     */
    readonly packageUpdateMechanism: string;
    /**
     * Package version.
     */
    readonly packageVersion: string;
    /**
     * Runtime name.
     */
    readonly runtimeName: string;
    /**
     * Runtime version.
     */
    readonly runtimeVersion: string;
    /**
     * SQLite version.
     */
    readonly sqliteVersion: string;
    /**
     * Start time.
     */
    readonly startTime: string;
    /**
     * Startup path.
     */
    readonly startupPath: string;
    /**
     * Version.
     */
    readonly version: string;
}
