// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Metadata -->Single Metadata.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Metadata.getMetadata({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadata(args: GetMetadataArgs, opts?: pulumi.InvokeOptions): Promise<GetMetadataResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Metadata/getMetadata:getMetadata", {
        "episodeImages": args.episodeImages,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getMetadata.
 */
export interface GetMetadataArgs {
    /**
     * Episode images flag.
     */
    episodeImages?: boolean;
    /**
     * Metadata name.
     */
    name: string;
}

/**
 * A collection of values returned by getMetadata.
 */
export interface GetMetadataResult {
    /**
     * Metadata configuration template.
     */
    readonly configContract: string;
    /**
     * Enable flag.
     */
    readonly enable: boolean;
    /**
     * Episode images flag.
     */
    readonly episodeImages?: boolean;
    /**
     * Episode metadata flag.
     */
    readonly episodeMetadata: boolean;
    /**
     * Metadata ID.
     */
    readonly id: number;
    /**
     * Metadata implementation name.
     */
    readonly implementation: string;
    /**
     * Metadata name.
     */
    readonly name: string;
    /**
     * Season images flag.
     */
    readonly seasonImages: boolean;
    /**
     * Series images flag.
     */
    readonly seriesImages: boolean;
    /**
     * Series metadata flag.
     */
    readonly seriesMetadata: boolean;
    /**
     * Series metadata URL flag.
     */
    readonly seriesMetadataUrl: boolean;
    /**
     * List of associated tags.
     */
    readonly tags: number[];
}
/**
 * <!-- subcategory:Metadata -->Single Metadata.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Metadata.getMetadata({
 *     name: "Example",
 * });
 * ```
 */
export function getMetadataOutput(args: GetMetadataOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMetadataResult> {
    return pulumi.output(args).apply((a: any) => getMetadata(a, opts))
}

/**
 * A collection of arguments for invoking getMetadata.
 */
export interface GetMetadataOutputArgs {
    /**
     * Episode images flag.
     */
    episodeImages?: pulumi.Input<boolean>;
    /**
     * Metadata name.
     */
    name: pulumi.Input<string>;
}
