// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Metadata -->Generic Metadata resource. When possible use a specific resource instead.
 * For more information refer to [Metadata](https://wiki.servarr.com/sonarr/settings#metadata) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@maienm/pulumi-sonarr";
 *
 * const example = new sonarr.metadata.Metadata("example", {
 *     configContract: "MediaBrowserMetadataSettings",
 *     enable: true,
 *     episodeImages: false,
 *     episodeMetadata: true,
 *     implementation: "MediaBrowserMetadata",
 *     name: "Example",
 *     seasonImages: true,
 *     seriesImages: false,
 *     tags: [
 *         1,
 *         2,
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import sonarr:Metadata/metadata:Metadata example 1
 * ```
 */
export class Metadata extends pulumi.CustomResource {
    /**
     * Get an existing Metadata resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MetadataState, opts?: pulumi.CustomResourceOptions): Metadata {
        return new Metadata(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarr:Metadata/metadata:Metadata';

    /**
     * Returns true if the given object is an instance of Metadata.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Metadata {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Metadata.__pulumiType;
    }

    /**
     * Metadata configuration template.
     */
    public readonly configContract!: pulumi.Output<string>;
    /**
     * Enable flag.
     */
    public readonly enable!: pulumi.Output<boolean>;
    /**
     * Episode images flag.
     */
    public readonly episodeImages!: pulumi.Output<boolean>;
    /**
     * Episode metadata flag.
     */
    public readonly episodeMetadata!: pulumi.Output<boolean>;
    /**
     * Metadata implementation name.
     */
    public readonly implementation!: pulumi.Output<string>;
    /**
     * Metadata name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Season images flag.
     */
    public readonly seasonImages!: pulumi.Output<boolean>;
    /**
     * Series images flag.
     */
    public readonly seriesImages!: pulumi.Output<boolean>;
    /**
     * Series metadata flag.
     */
    public readonly seriesMetadata!: pulumi.Output<boolean>;
    /**
     * Series metadata URL flag.
     */
    public readonly seriesMetadataUrl!: pulumi.Output<boolean>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;

    /**
     * Create a Metadata resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MetadataArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MetadataArgs | MetadataState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MetadataState | undefined;
            resourceInputs["configContract"] = state ? state.configContract : undefined;
            resourceInputs["enable"] = state ? state.enable : undefined;
            resourceInputs["episodeImages"] = state ? state.episodeImages : undefined;
            resourceInputs["episodeMetadata"] = state ? state.episodeMetadata : undefined;
            resourceInputs["implementation"] = state ? state.implementation : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["seasonImages"] = state ? state.seasonImages : undefined;
            resourceInputs["seriesImages"] = state ? state.seriesImages : undefined;
            resourceInputs["seriesMetadata"] = state ? state.seriesMetadata : undefined;
            resourceInputs["seriesMetadataUrl"] = state ? state.seriesMetadataUrl : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as MetadataArgs | undefined;
            if ((!args || args.configContract === undefined) && !opts.urn) {
                throw new Error("Missing required property 'configContract'");
            }
            if ((!args || args.implementation === undefined) && !opts.urn) {
                throw new Error("Missing required property 'implementation'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["configContract"] = args ? args.configContract : undefined;
            resourceInputs["enable"] = args ? args.enable : undefined;
            resourceInputs["episodeImages"] = args ? args.episodeImages : undefined;
            resourceInputs["episodeMetadata"] = args ? args.episodeMetadata : undefined;
            resourceInputs["implementation"] = args ? args.implementation : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["seasonImages"] = args ? args.seasonImages : undefined;
            resourceInputs["seriesImages"] = args ? args.seriesImages : undefined;
            resourceInputs["seriesMetadata"] = args ? args.seriesMetadata : undefined;
            resourceInputs["seriesMetadataUrl"] = args ? args.seriesMetadataUrl : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Metadata.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Metadata resources.
 */
export interface MetadataState {
    /**
     * Metadata configuration template.
     */
    configContract?: pulumi.Input<string>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Episode images flag.
     */
    episodeImages?: pulumi.Input<boolean>;
    /**
     * Episode metadata flag.
     */
    episodeMetadata?: pulumi.Input<boolean>;
    /**
     * Metadata implementation name.
     */
    implementation?: pulumi.Input<string>;
    /**
     * Metadata name.
     */
    name?: pulumi.Input<string>;
    /**
     * Season images flag.
     */
    seasonImages?: pulumi.Input<boolean>;
    /**
     * Series images flag.
     */
    seriesImages?: pulumi.Input<boolean>;
    /**
     * Series metadata flag.
     */
    seriesMetadata?: pulumi.Input<boolean>;
    /**
     * Series metadata URL flag.
     */
    seriesMetadataUrl?: pulumi.Input<boolean>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}

/**
 * The set of arguments for constructing a Metadata resource.
 */
export interface MetadataArgs {
    /**
     * Metadata configuration template.
     */
    configContract: pulumi.Input<string>;
    /**
     * Enable flag.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * Episode images flag.
     */
    episodeImages?: pulumi.Input<boolean>;
    /**
     * Episode metadata flag.
     */
    episodeMetadata?: pulumi.Input<boolean>;
    /**
     * Metadata implementation name.
     */
    implementation: pulumi.Input<string>;
    /**
     * Metadata name.
     */
    name: pulumi.Input<string>;
    /**
     * Season images flag.
     */
    seasonImages?: pulumi.Input<boolean>;
    /**
     * Series images flag.
     */
    seriesImages?: pulumi.Input<boolean>;
    /**
     * Series metadata flag.
     */
    seriesMetadata?: pulumi.Input<boolean>;
    /**
     * Series metadata URL flag.
     */
    seriesMetadataUrl?: pulumi.Input<boolean>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
}
