// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Series -->Single Series.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Series.getSeries({
 *     title: "Friends",
 * });
 * ```
 */
export function getSeries(args: GetSeriesArgs, opts?: pulumi.InvokeOptions): Promise<GetSeriesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Series/getSeries:getSeries", {
        "title": args.title,
    }, opts);
}

/**
 * A collection of arguments for invoking getSeries.
 */
export interface GetSeriesArgs {
    /**
     * Series Title.
     */
    title: string;
}

/**
 * A collection of values returned by getSeries.
 */
export interface GetSeriesResult {
    /**
     * Series ID.
     */
    readonly id: number;
    /**
     * Monitored flag.
     */
    readonly monitored: boolean;
    /**
     * Series Path.
     */
    readonly path: string;
    /**
     * Quality Profile ID.
     */
    readonly qualityProfileId: number;
    /**
     * Series Root Folder.
     */
    readonly rootFolderPath: string;
    /**
     * Season Folder flag.
     */
    readonly seasonFolder: boolean;
    /**
     * List of associated tags.
     */
    readonly tags: number[];
    /**
     * Series Title.
     */
    readonly title: string;
    /**
     * Series Title in kebab format.
     */
    readonly titleSlug: string;
    /**
     * TVDB ID.
     */
    readonly tvdbId: number;
    /**
     * Scene numbering flag.
     */
    readonly useSceneNumbering: boolean;
}
/**
 * <!-- subcategory:Series -->Single Series.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Series.getSeries({
 *     title: "Friends",
 * });
 * ```
 */
export function getSeriesOutput(args: GetSeriesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSeriesResult> {
    return pulumi.output(args).apply((a: any) => getSeries(a, opts))
}

/**
 * A collection of arguments for invoking getSeries.
 */
export interface GetSeriesOutputArgs {
    /**
     * Series Title.
     */
    title: pulumi.Input<string>;
}
