// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -> Custom Format Condition Release Group data source.
 * For more information refer to [Custom Format Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 *
 * {{% examples %}}
 * ## Example Usage
 * {{% example %}}
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@maienm/pulumi-sonarr";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const exampleCustomFormatConditionReleaseGroup = sonarr.Profiles.getCustomFormatConditionReleaseGroup({
 *     name: "HDBits",
 *     negate: false,
 *     required: false,
 *     value: ".*HDBits.*",
 * });
 * const exampleCustomFormat = new sonarr.profiles.CustomFormat("exampleCustomFormat", {
 *     includeCustomFormatWhenRenaming: false,
 *     name: "Example",
 *     specifications: [exampleCustomFormatConditionReleaseGroup],
 * });
 * ```
 * {{% /example %}}
 * {{% /examples %}}
 */
export function getCustomFormatConditionReleaseGroup(args: GetCustomFormatConditionReleaseGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomFormatConditionReleaseGroupResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Profiles/getCustomFormatConditionReleaseGroup:getCustomFormatConditionReleaseGroup", {
        "name": args.name,
        "negate": args.negate,
        "required": args.required,
        "value": args.value,
    }, opts);
}

/**
 * A collection of arguments for invoking getCustomFormatConditionReleaseGroup.
 */
export interface GetCustomFormatConditionReleaseGroupArgs {
    /**
     * Specification name.
     */
    name: string;
    /**
     * Negate flag.
     */
    negate: boolean;
    /**
     * Computed flag.
     */
    required: boolean;
    /**
     * Release group RegEx.
     */
    value: string;
}

/**
 * A collection of values returned by getCustomFormatConditionReleaseGroup.
 */
export interface GetCustomFormatConditionReleaseGroupResult {
    /**
     * Custom format condition release group ID.
     */
    readonly id: number;
    /**
     * Implementation.
     */
    readonly implementation: string;
    /**
     * Specification name.
     */
    readonly name: string;
    /**
     * Negate flag.
     */
    readonly negate: boolean;
    /**
     * Computed flag.
     */
    readonly required: boolean;
    /**
     * Release group RegEx.
     */
    readonly value: string;
}
/**
 * <!-- subcategory:Profiles -> Custom Format Condition Release Group data source.
 * For more information refer to [Custom Format Conditions](https://wiki.servarr.com/sonarr/settings#conditions).
 *
 * {{% examples %}}
 * ## Example Usage
 * {{% example %}}
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@maienm/pulumi-sonarr";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const exampleCustomFormatConditionReleaseGroup = sonarr.Profiles.getCustomFormatConditionReleaseGroup({
 *     name: "HDBits",
 *     negate: false,
 *     required: false,
 *     value: ".*HDBits.*",
 * });
 * const exampleCustomFormat = new sonarr.profiles.CustomFormat("exampleCustomFormat", {
 *     includeCustomFormatWhenRenaming: false,
 *     name: "Example",
 *     specifications: [exampleCustomFormatConditionReleaseGroup],
 * });
 * ```
 * {{% /example %}}
 * {{% /examples %}}
 */
export function getCustomFormatConditionReleaseGroupOutput(args: GetCustomFormatConditionReleaseGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCustomFormatConditionReleaseGroupResult> {
    return pulumi.output(args).apply((a: any) => getCustomFormatConditionReleaseGroup(a, opts))
}

/**
 * A collection of arguments for invoking getCustomFormatConditionReleaseGroup.
 */
export interface GetCustomFormatConditionReleaseGroupOutputArgs {
    /**
     * Specification name.
     */
    name: pulumi.Input<string>;
    /**
     * Negate flag.
     */
    negate: pulumi.Input<boolean>;
    /**
     * Computed flag.
     */
    required: pulumi.Input<boolean>;
    /**
     * Release group RegEx.
     */
    value: pulumi.Input<string>;
}
