// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->List all available Delay Profiles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Profiles.getDelayProfiles({});
 * ```
 */
export function getDelayProfiles(opts?: pulumi.InvokeOptions): Promise<GetDelayProfilesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Profiles/getDelayProfiles:getDelayProfiles", {
    }, opts);
}

/**
 * A collection of values returned by getDelayProfiles.
 */
export interface GetDelayProfilesResult {
    /**
     * Delay Profile list.
     */
    readonly delayProfiles: outputs.Profiles.GetDelayProfilesDelayProfile[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
