// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->List all available Release Profiles.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Profiles.getReleaseProfiles({});
 * ```
 */
export function getReleaseProfiles(opts?: pulumi.InvokeOptions): Promise<GetReleaseProfilesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Profiles/getReleaseProfiles:getReleaseProfiles", {
    }, opts);
}

/**
 * A collection of values returned by getReleaseProfiles.
 */
export interface GetReleaseProfilesResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * Release Profile list.
     */
    readonly releaseProfiles: outputs.Profiles.GetReleaseProfilesReleaseProfile[];
}
