// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Profiles -->Single Release Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Profiles.getReleaseProfile({
 *     id: 1,
 * });
 * ```
 */
export function getReleaseProfile(args: GetReleaseProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetReleaseProfileResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Profiles/getReleaseProfile:getReleaseProfile", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getReleaseProfile.
 */
export interface GetReleaseProfileArgs {
    /**
     * Release Profile ID.
     */
    id: number;
}

/**
 * A collection of values returned by getReleaseProfile.
 */
export interface GetReleaseProfileResult {
    /**
     * Enabled
     */
    readonly enabled: boolean;
    /**
     * Release Profile ID.
     */
    readonly id: number;
    /**
     * Ignored terms.
     */
    readonly ignoreds: string[];
    /**
     * Indexer ID. Set `0` for all.
     */
    readonly indexerId: number;
    /**
     * Release profile name.
     */
    readonly name: string;
    /**
     * Required terms.
     */
    readonly requireds: string[];
    /**
     * List of associated tags.
     */
    readonly tags: number[];
}
/**
 * <!-- subcategory:Profiles -->Single Release Profile.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Profiles.getReleaseProfile({
 *     id: 1,
 * });
 * ```
 */
export function getReleaseProfileOutput(args: GetReleaseProfileOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetReleaseProfileResult> {
    return pulumi.output(args).apply((a: any) => getReleaseProfile(a, opts))
}

/**
 * A collection of arguments for invoking getReleaseProfile.
 */
export interface GetReleaseProfileOutputArgs {
    /**
     * Release Profile ID.
     */
    id: pulumi.Input<number>;
}
