// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Media Management -->Media Management.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.MediaManagement.getMediaManagement({});
 * ```
 */
export function getMediaManagement(opts?: pulumi.InvokeOptions): Promise<GetMediaManagementResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:MediaManagement/getMediaManagement:getMediaManagement", {
    }, opts);
}

/**
 * A collection of values returned by getMediaManagement.
 */
export interface GetMediaManagementResult {
    /**
     * Permission in linux format.
     */
    readonly chmodFolder: string;
    /**
     * Group used for permission.
     */
    readonly chownGroup: string;
    /**
     * Create empty series directories.
     */
    readonly createEmptyFolders: boolean;
    /**
     * Delete empty series directories.
     */
    readonly deleteEmptyFolders: boolean;
    /**
     * Download proper and repack policy. valid inputs are: 'preferAndUpgrade', 'doNotUpgrade', and 'doNotPrefer'.
     */
    readonly downloadPropersRepacks: string;
    /**
     * Scan files details.
     */
    readonly enableMediaInfo: boolean;
    /**
     * Episode title requirement policy. valid inputs are: 'always', 'bulkSeasonReleases' and 'never'.
     */
    readonly episodeTitleRequired: string;
    /**
     * Comma separated list of extra files to import (.nfo will be imported as .nfo-orig).
     */
    readonly extraFileExtensions: string;
    /**
     * Define the file date modification. valid inputs are: 'none', 'localAirDate, and 'utcAirDate'.
     */
    readonly fileDate: string;
    /**
     * Use hardlinks instead of copy.
     */
    readonly hardlinksCopy: boolean;
    /**
     * Delay Profile ID.
     */
    readonly id: number;
    /**
     * Import extra files. If enabled it will leverage 'extra*file*extensions'.
     */
    readonly importExtraFiles: boolean;
    /**
     * Minimum free space in MB to allow import.
     */
    readonly minimumFreeSpace: number;
    /**
     * Recyle bin days of retention.
     */
    readonly recycleBinDays: number;
    /**
     * Recycle bin absolute path.
     */
    readonly recycleBinPath: string;
    /**
     * Rescan after refresh policy. valid inputs are: 'always', 'afterManual' and 'never'.
     */
    readonly rescanAfterRefresh: string;
    /**
     * Set permission for imported files.
     */
    readonly setPermissions: boolean;
    /**
     * Skip free space check before importing.
     */
    readonly skipFreeSpaceCheck: boolean;
    /**
     * Unmonitor deleted files.
     */
    readonly unmonitorPreviousEpisodes: boolean;
}
