// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Download Clients -->Single Download Client.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.ImportLists.getImportList({
 *     name: "Example",
 * });
 * ```
 */
export function getImportList(args: GetImportListArgs, opts?: pulumi.InvokeOptions): Promise<GetImportListResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:ImportLists/getImportList:getImportList", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getImportList.
 */
export interface GetImportListArgs {
    /**
     * Import List name.
     */
    name: string;
}

/**
 * A collection of values returned by getImportList.
 */
export interface GetImportListResult {
    /**
     * Access token.
     */
    readonly accessToken: string;
    /**
     * API key.
     */
    readonly apiKey: string;
    /**
     * Auth User.
     */
    readonly authUser: string;
    /**
     * Base URL.
     */
    readonly baseUrl: string;
    /**
     * ImportList configuration template.
     */
    readonly configContract: string;
    /**
     * Enable automatic add flag.
     */
    readonly enableAutomaticAdd: boolean;
    /**
     * Expires.
     */
    readonly expires: string;
    /**
     * Genres.
     */
    readonly genres: string;
    /**
     * Import List ID.
     */
    readonly id: number;
    /**
     * ImportList implementation name.
     */
    readonly implementation: string;
    /**
     * Language profile IDs.
     */
    readonly languageProfileIds: number[];
    /**
     * Limit.
     */
    readonly limit: number;
    /**
     * List ID.
     */
    readonly listId: string;
    /**
     * Simkl list type.
     */
    readonly listType: number;
    /**
     * List name.
     */
    readonly listname: string;
    /**
     * Import List name.
     */
    readonly name: string;
    /**
     * Quality profile ID.
     */
    readonly qualityProfileId: number;
    /**
     * Quality profile IDs.
     */
    readonly qualityProfileIds: number[];
    /**
     * Rating.
     */
    readonly rating: string;
    /**
     * Refresh token.
     */
    readonly refreshToken: string;
    /**
     * Root folder path.
     */
    readonly rootFolderPath: string;
    /**
     * Season folder flag.
     */
    readonly seasonFolder: boolean;
    /**
     * Series type.
     */
    readonly seriesType: string;
    /**
     * Should monitor.
     */
    readonly shouldMonitor: string;
    /**
     * Tag IDs.
     */
    readonly tagIds: number[];
    /**
     * List of associated tags.
     */
    readonly tags: number[];
    /**
     * Trakt additional parameters.
     */
    readonly traktAdditionalParameters: string;
    /**
     * Trakt list type.
     */
    readonly traktListType: number;
    /**
     * URL.
     */
    readonly url: string;
    /**
     * Username.
     */
    readonly username: string;
    /**
     * Years.
     */
    readonly years: string;
}
/**
 * <!-- subcategory:Download Clients -->Single Download Client.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.ImportLists.getImportList({
 *     name: "Example",
 * });
 * ```
 */
export function getImportListOutput(args: GetImportListOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetImportListResult> {
    return pulumi.output(args).apply((a: any) => getImportList(a, opts))
}

/**
 * A collection of arguments for invoking getImportList.
 */
export interface GetImportListOutputArgs {
    /**
     * Import List name.
     */
    name: pulumi.Input<string>;
}
