// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Import List Exclusion resource.
 * For more information refer to [ImportListExclusions](https://wiki.servarr.com/sonarr/settings#list-exclusions) documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@maienm/pulumi-sonarr";
 *
 * const example = new sonarr.importlists.ImportListExclusion("example", {
 *     title: "Friends",
 *     tvdbId: 79168,
 * });
 * ```
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import sonarr:ImportLists/importListExclusion:ImportListExclusion example 10
 * ```
 */
export class ImportListExclusion extends pulumi.CustomResource {
    /**
     * Get an existing ImportListExclusion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListExclusionState, opts?: pulumi.CustomResourceOptions): ImportListExclusion {
        return new ImportListExclusion(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarr:ImportLists/importListExclusion:ImportListExclusion';

    /**
     * Returns true if the given object is an instance of ImportListExclusion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportListExclusion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportListExclusion.__pulumiType;
    }

    /**
     * Series to be excluded.
     */
    public readonly title!: pulumi.Output<string>;
    /**
     * Series TVDB ID.
     */
    public readonly tvdbId!: pulumi.Output<number>;

    /**
     * Create a ImportListExclusion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListExclusionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListExclusionArgs | ImportListExclusionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListExclusionState | undefined;
            resourceInputs["title"] = state ? state.title : undefined;
            resourceInputs["tvdbId"] = state ? state.tvdbId : undefined;
        } else {
            const args = argsOrState as ImportListExclusionArgs | undefined;
            if ((!args || args.title === undefined) && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            if ((!args || args.tvdbId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'tvdbId'");
            }
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["tvdbId"] = args ? args.tvdbId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ImportListExclusion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportListExclusion resources.
 */
export interface ImportListExclusionState {
    /**
     * Series to be excluded.
     */
    title?: pulumi.Input<string>;
    /**
     * Series TVDB ID.
     */
    tvdbId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a ImportListExclusion resource.
 */
export interface ImportListExclusionArgs {
    /**
     * Series to be excluded.
     */
    title: pulumi.Input<string>;
    /**
     * Series TVDB ID.
     */
    tvdbId: pulumi.Input<number>;
}
