// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->Generic Import List resource. When possible use a specific resource instead.
 * For more information refer to [Import List](https://wiki.servarr.com/sonarr/settings#import-lists).
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import sonarr:ImportLists/importList:ImportList example 1
 * ```
 */
export class ImportList extends pulumi.CustomResource {
    /**
     * Get an existing ImportList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListState, opts?: pulumi.CustomResourceOptions): ImportList {
        return new ImportList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarr:ImportLists/importList:ImportList';

    /**
     * Returns true if the given object is an instance of ImportList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportList.__pulumiType;
    }

    /**
     * Access token.
     */
    public readonly accessToken!: pulumi.Output<string>;
    /**
     * API key.
     */
    public readonly apiKey!: pulumi.Output<string>;
    /**
     * Auth User.
     */
    public readonly authUser!: pulumi.Output<string>;
    /**
     * Base URL.
     */
    public readonly baseUrl!: pulumi.Output<string>;
    /**
     * ImportList configuration template.
     */
    public readonly configContract!: pulumi.Output<string>;
    /**
     * Enable automatic add flag.
     */
    public readonly enableAutomaticAdd!: pulumi.Output<boolean>;
    /**
     * Expires.
     */
    public readonly expires!: pulumi.Output<string>;
    /**
     * Genres.
     */
    public readonly genres!: pulumi.Output<string>;
    /**
     * ImportList implementation name.
     */
    public readonly implementation!: pulumi.Output<string>;
    /**
     * Language profile IDs.
     */
    public readonly languageProfileIds!: pulumi.Output<number[]>;
    /**
     * Limit.
     */
    public readonly limit!: pulumi.Output<number>;
    /**
     * List ID.
     */
    public readonly listId!: pulumi.Output<string>;
    /**
     * Simkl list type.
     */
    public readonly listType!: pulumi.Output<number>;
    /**
     * List name.
     */
    public readonly listname!: pulumi.Output<string>;
    /**
     * Import List name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Quality profile ID.
     */
    public readonly qualityProfileId!: pulumi.Output<number>;
    /**
     * Quality profile IDs.
     */
    public readonly qualityProfileIds!: pulumi.Output<number[]>;
    /**
     * Rating.
     */
    public readonly rating!: pulumi.Output<string>;
    /**
     * Refresh token.
     */
    public readonly refreshToken!: pulumi.Output<string>;
    /**
     * Root folder path.
     */
    public readonly rootFolderPath!: pulumi.Output<string>;
    /**
     * Season folder flag.
     */
    public readonly seasonFolder!: pulumi.Output<boolean>;
    /**
     * Series type.
     */
    public readonly seriesType!: pulumi.Output<string>;
    /**
     * Should monitor.
     */
    public readonly shouldMonitor!: pulumi.Output<string>;
    /**
     * Tag IDs.
     */
    public readonly tagIds!: pulumi.Output<number[]>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;
    /**
     * Trakt additional parameters.
     */
    public readonly traktAdditionalParameters!: pulumi.Output<string>;
    /**
     * Trakt list type.
     */
    public readonly traktListType!: pulumi.Output<number>;
    /**
     * URL.
     */
    public readonly url!: pulumi.Output<string>;
    /**
     * Username.
     */
    public readonly username!: pulumi.Output<string>;
    /**
     * Years.
     */
    public readonly years!: pulumi.Output<string>;

    /**
     * Create a ImportList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListArgs | ImportListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListState | undefined;
            resourceInputs["accessToken"] = state ? state.accessToken : undefined;
            resourceInputs["apiKey"] = state ? state.apiKey : undefined;
            resourceInputs["authUser"] = state ? state.authUser : undefined;
            resourceInputs["baseUrl"] = state ? state.baseUrl : undefined;
            resourceInputs["configContract"] = state ? state.configContract : undefined;
            resourceInputs["enableAutomaticAdd"] = state ? state.enableAutomaticAdd : undefined;
            resourceInputs["expires"] = state ? state.expires : undefined;
            resourceInputs["genres"] = state ? state.genres : undefined;
            resourceInputs["implementation"] = state ? state.implementation : undefined;
            resourceInputs["languageProfileIds"] = state ? state.languageProfileIds : undefined;
            resourceInputs["limit"] = state ? state.limit : undefined;
            resourceInputs["listId"] = state ? state.listId : undefined;
            resourceInputs["listType"] = state ? state.listType : undefined;
            resourceInputs["listname"] = state ? state.listname : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["qualityProfileId"] = state ? state.qualityProfileId : undefined;
            resourceInputs["qualityProfileIds"] = state ? state.qualityProfileIds : undefined;
            resourceInputs["rating"] = state ? state.rating : undefined;
            resourceInputs["refreshToken"] = state ? state.refreshToken : undefined;
            resourceInputs["rootFolderPath"] = state ? state.rootFolderPath : undefined;
            resourceInputs["seasonFolder"] = state ? state.seasonFolder : undefined;
            resourceInputs["seriesType"] = state ? state.seriesType : undefined;
            resourceInputs["shouldMonitor"] = state ? state.shouldMonitor : undefined;
            resourceInputs["tagIds"] = state ? state.tagIds : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["traktAdditionalParameters"] = state ? state.traktAdditionalParameters : undefined;
            resourceInputs["traktListType"] = state ? state.traktListType : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
            resourceInputs["username"] = state ? state.username : undefined;
            resourceInputs["years"] = state ? state.years : undefined;
        } else {
            const args = argsOrState as ImportListArgs | undefined;
            if ((!args || args.configContract === undefined) && !opts.urn) {
                throw new Error("Missing required property 'configContract'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.seriesType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'seriesType'");
            }
            resourceInputs["accessToken"] = args?.accessToken ? pulumi.secret(args.accessToken) : undefined;
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["authUser"] = args ? args.authUser : undefined;
            resourceInputs["baseUrl"] = args ? args.baseUrl : undefined;
            resourceInputs["configContract"] = args ? args.configContract : undefined;
            resourceInputs["enableAutomaticAdd"] = args ? args.enableAutomaticAdd : undefined;
            resourceInputs["expires"] = args ? args.expires : undefined;
            resourceInputs["genres"] = args ? args.genres : undefined;
            resourceInputs["implementation"] = args ? args.implementation : undefined;
            resourceInputs["languageProfileIds"] = args ? args.languageProfileIds : undefined;
            resourceInputs["limit"] = args ? args.limit : undefined;
            resourceInputs["listId"] = args ? args.listId : undefined;
            resourceInputs["listType"] = args ? args.listType : undefined;
            resourceInputs["listname"] = args ? args.listname : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["qualityProfileId"] = args ? args.qualityProfileId : undefined;
            resourceInputs["qualityProfileIds"] = args ? args.qualityProfileIds : undefined;
            resourceInputs["rating"] = args ? args.rating : undefined;
            resourceInputs["refreshToken"] = args?.refreshToken ? pulumi.secret(args.refreshToken) : undefined;
            resourceInputs["rootFolderPath"] = args ? args.rootFolderPath : undefined;
            resourceInputs["seasonFolder"] = args ? args.seasonFolder : undefined;
            resourceInputs["seriesType"] = args ? args.seriesType : undefined;
            resourceInputs["shouldMonitor"] = args ? args.shouldMonitor : undefined;
            resourceInputs["tagIds"] = args ? args.tagIds : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["traktAdditionalParameters"] = args ? args.traktAdditionalParameters : undefined;
            resourceInputs["traktListType"] = args ? args.traktListType : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
            resourceInputs["years"] = args ? args.years : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessToken", "apiKey", "refreshToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ImportList.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportList resources.
 */
export interface ImportListState {
    /**
     * Access token.
     */
    accessToken?: pulumi.Input<string>;
    /**
     * API key.
     */
    apiKey?: pulumi.Input<string>;
    /**
     * Auth User.
     */
    authUser?: pulumi.Input<string>;
    /**
     * Base URL.
     */
    baseUrl?: pulumi.Input<string>;
    /**
     * ImportList configuration template.
     */
    configContract?: pulumi.Input<string>;
    /**
     * Enable automatic add flag.
     */
    enableAutomaticAdd?: pulumi.Input<boolean>;
    /**
     * Expires.
     */
    expires?: pulumi.Input<string>;
    /**
     * Genres.
     */
    genres?: pulumi.Input<string>;
    /**
     * ImportList implementation name.
     */
    implementation?: pulumi.Input<string>;
    /**
     * Language profile IDs.
     */
    languageProfileIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Limit.
     */
    limit?: pulumi.Input<number>;
    /**
     * List ID.
     */
    listId?: pulumi.Input<string>;
    /**
     * Simkl list type.
     */
    listType?: pulumi.Input<number>;
    /**
     * List name.
     */
    listname?: pulumi.Input<string>;
    /**
     * Import List name.
     */
    name?: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId?: pulumi.Input<number>;
    /**
     * Quality profile IDs.
     */
    qualityProfileIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Rating.
     */
    rating?: pulumi.Input<string>;
    /**
     * Refresh token.
     */
    refreshToken?: pulumi.Input<string>;
    /**
     * Root folder path.
     */
    rootFolderPath?: pulumi.Input<string>;
    /**
     * Season folder flag.
     */
    seasonFolder?: pulumi.Input<boolean>;
    /**
     * Series type.
     */
    seriesType?: pulumi.Input<string>;
    /**
     * Should monitor.
     */
    shouldMonitor?: pulumi.Input<string>;
    /**
     * Tag IDs.
     */
    tagIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Trakt additional parameters.
     */
    traktAdditionalParameters?: pulumi.Input<string>;
    /**
     * Trakt list type.
     */
    traktListType?: pulumi.Input<number>;
    /**
     * URL.
     */
    url?: pulumi.Input<string>;
    /**
     * Username.
     */
    username?: pulumi.Input<string>;
    /**
     * Years.
     */
    years?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ImportList resource.
 */
export interface ImportListArgs {
    /**
     * Access token.
     */
    accessToken?: pulumi.Input<string>;
    /**
     * API key.
     */
    apiKey?: pulumi.Input<string>;
    /**
     * Auth User.
     */
    authUser?: pulumi.Input<string>;
    /**
     * Base URL.
     */
    baseUrl?: pulumi.Input<string>;
    /**
     * ImportList configuration template.
     */
    configContract: pulumi.Input<string>;
    /**
     * Enable automatic add flag.
     */
    enableAutomaticAdd?: pulumi.Input<boolean>;
    /**
     * Expires.
     */
    expires?: pulumi.Input<string>;
    /**
     * Genres.
     */
    genres?: pulumi.Input<string>;
    /**
     * ImportList implementation name.
     */
    implementation?: pulumi.Input<string>;
    /**
     * Language profile IDs.
     */
    languageProfileIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Limit.
     */
    limit?: pulumi.Input<number>;
    /**
     * List ID.
     */
    listId?: pulumi.Input<string>;
    /**
     * Simkl list type.
     */
    listType?: pulumi.Input<number>;
    /**
     * List name.
     */
    listname?: pulumi.Input<string>;
    /**
     * Import List name.
     */
    name: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId?: pulumi.Input<number>;
    /**
     * Quality profile IDs.
     */
    qualityProfileIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Rating.
     */
    rating?: pulumi.Input<string>;
    /**
     * Refresh token.
     */
    refreshToken?: pulumi.Input<string>;
    /**
     * Root folder path.
     */
    rootFolderPath?: pulumi.Input<string>;
    /**
     * Season folder flag.
     */
    seasonFolder?: pulumi.Input<boolean>;
    /**
     * Series type.
     */
    seriesType: pulumi.Input<string>;
    /**
     * Should monitor.
     */
    shouldMonitor?: pulumi.Input<string>;
    /**
     * Tag IDs.
     */
    tagIds?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Trakt additional parameters.
     */
    traktAdditionalParameters?: pulumi.Input<string>;
    /**
     * Trakt list type.
     */
    traktListType?: pulumi.Input<number>;
    /**
     * URL.
     */
    url?: pulumi.Input<string>;
    /**
     * Username.
     */
    username?: pulumi.Input<string>;
    /**
     * Years.
     */
    years?: pulumi.Input<string>;
}
