// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Import Lists -->ImportList TraktPopular resource.
 * For more information refer to [Import List](https://wiki.servarr.com/sonarr/settings#import-lists) and [TraktPopular](https://wiki.servarr.com/sonarr/supported#trakt_popular).
 *
 * ## Import
 *
 * import using the API/UI ID
 *
 * ```sh
 *  $ pulumi import sonarr:ImportLists/importListTraktPopular:ImportListTraktPopular example 1
 * ```
 */
export class ImportListTraktPopular extends pulumi.CustomResource {
    /**
     * Get an existing ImportListTraktPopular resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ImportListTraktPopularState, opts?: pulumi.CustomResourceOptions): ImportListTraktPopular {
        return new ImportListTraktPopular(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarr:ImportLists/importListTraktPopular:ImportListTraktPopular';

    /**
     * Returns true if the given object is an instance of ImportListTraktPopular.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ImportListTraktPopular {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ImportListTraktPopular.__pulumiType;
    }

    /**
     * Access token.
     */
    public readonly accessToken!: pulumi.Output<string>;
    /**
     * Auth User.
     */
    public readonly authUser!: pulumi.Output<string>;
    /**
     * Enable automatic add flag.
     */
    public readonly enableAutomaticAdd!: pulumi.Output<boolean>;
    /**
     * Expires.
     */
    public readonly expires!: pulumi.Output<string>;
    /**
     * Genres.
     */
    public readonly genres!: pulumi.Output<string>;
    /**
     * Limit.
     */
    public readonly limit!: pulumi.Output<number>;
    /**
     * Import List name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Quality profile ID.
     */
    public readonly qualityProfileId!: pulumi.Output<number>;
    /**
     * Rating.
     */
    public readonly rating!: pulumi.Output<string>;
    /**
     * Refresh token.
     */
    public readonly refreshToken!: pulumi.Output<string>;
    /**
     * Root folder path.
     */
    public readonly rootFolderPath!: pulumi.Output<string>;
    /**
     * Season folder flag.
     */
    public readonly seasonFolder!: pulumi.Output<boolean>;
    /**
     * Series type.
     */
    public readonly seriesType!: pulumi.Output<string>;
    /**
     * Should monitor.
     */
    public readonly shouldMonitor!: pulumi.Output<string>;
    /**
     * List of associated tags.
     */
    public readonly tags!: pulumi.Output<number[]>;
    /**
     * Trakt additional parameters.
     */
    public readonly traktAdditionalParameters!: pulumi.Output<string>;
    /**
     * Trakt list type. '0' Trending, '1' Popular, '2' Anticipated, '3' TopWatchedByWeek, '4' TopWatchedByMonth, '5' TopWatchedByYear, '6' TopWatchedByAllTime, '7' RecommendedByWeek, '8' RecommendedByMonth, '9' RecommendedByYear, '10' RecommendedByAllTime.
     */
    public readonly traktListType!: pulumi.Output<number>;
    /**
     * Years.
     */
    public readonly years!: pulumi.Output<string>;

    /**
     * Create a ImportListTraktPopular resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ImportListTraktPopularArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ImportListTraktPopularArgs | ImportListTraktPopularState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ImportListTraktPopularState | undefined;
            resourceInputs["accessToken"] = state ? state.accessToken : undefined;
            resourceInputs["authUser"] = state ? state.authUser : undefined;
            resourceInputs["enableAutomaticAdd"] = state ? state.enableAutomaticAdd : undefined;
            resourceInputs["expires"] = state ? state.expires : undefined;
            resourceInputs["genres"] = state ? state.genres : undefined;
            resourceInputs["limit"] = state ? state.limit : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["qualityProfileId"] = state ? state.qualityProfileId : undefined;
            resourceInputs["rating"] = state ? state.rating : undefined;
            resourceInputs["refreshToken"] = state ? state.refreshToken : undefined;
            resourceInputs["rootFolderPath"] = state ? state.rootFolderPath : undefined;
            resourceInputs["seasonFolder"] = state ? state.seasonFolder : undefined;
            resourceInputs["seriesType"] = state ? state.seriesType : undefined;
            resourceInputs["shouldMonitor"] = state ? state.shouldMonitor : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["traktAdditionalParameters"] = state ? state.traktAdditionalParameters : undefined;
            resourceInputs["traktListType"] = state ? state.traktListType : undefined;
            resourceInputs["years"] = state ? state.years : undefined;
        } else {
            const args = argsOrState as ImportListTraktPopularArgs | undefined;
            if ((!args || args.enableAutomaticAdd === undefined) && !opts.urn) {
                throw new Error("Missing required property 'enableAutomaticAdd'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.qualityProfileId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'qualityProfileId'");
            }
            if ((!args || args.rootFolderPath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rootFolderPath'");
            }
            if ((!args || args.seasonFolder === undefined) && !opts.urn) {
                throw new Error("Missing required property 'seasonFolder'");
            }
            if ((!args || args.seriesType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'seriesType'");
            }
            if ((!args || args.shouldMonitor === undefined) && !opts.urn) {
                throw new Error("Missing required property 'shouldMonitor'");
            }
            if ((!args || args.traktListType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'traktListType'");
            }
            resourceInputs["accessToken"] = args?.accessToken ? pulumi.secret(args.accessToken) : undefined;
            resourceInputs["authUser"] = args ? args.authUser : undefined;
            resourceInputs["enableAutomaticAdd"] = args ? args.enableAutomaticAdd : undefined;
            resourceInputs["expires"] = args ? args.expires : undefined;
            resourceInputs["genres"] = args ? args.genres : undefined;
            resourceInputs["limit"] = args ? args.limit : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["qualityProfileId"] = args ? args.qualityProfileId : undefined;
            resourceInputs["rating"] = args ? args.rating : undefined;
            resourceInputs["refreshToken"] = args?.refreshToken ? pulumi.secret(args.refreshToken) : undefined;
            resourceInputs["rootFolderPath"] = args ? args.rootFolderPath : undefined;
            resourceInputs["seasonFolder"] = args ? args.seasonFolder : undefined;
            resourceInputs["seriesType"] = args ? args.seriesType : undefined;
            resourceInputs["shouldMonitor"] = args ? args.shouldMonitor : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["traktAdditionalParameters"] = args ? args.traktAdditionalParameters : undefined;
            resourceInputs["traktListType"] = args ? args.traktListType : undefined;
            resourceInputs["years"] = args ? args.years : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessToken", "refreshToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ImportListTraktPopular.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ImportListTraktPopular resources.
 */
export interface ImportListTraktPopularState {
    /**
     * Access token.
     */
    accessToken?: pulumi.Input<string>;
    /**
     * Auth User.
     */
    authUser?: pulumi.Input<string>;
    /**
     * Enable automatic add flag.
     */
    enableAutomaticAdd?: pulumi.Input<boolean>;
    /**
     * Expires.
     */
    expires?: pulumi.Input<string>;
    /**
     * Genres.
     */
    genres?: pulumi.Input<string>;
    /**
     * Limit.
     */
    limit?: pulumi.Input<number>;
    /**
     * Import List name.
     */
    name?: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId?: pulumi.Input<number>;
    /**
     * Rating.
     */
    rating?: pulumi.Input<string>;
    /**
     * Refresh token.
     */
    refreshToken?: pulumi.Input<string>;
    /**
     * Root folder path.
     */
    rootFolderPath?: pulumi.Input<string>;
    /**
     * Season folder flag.
     */
    seasonFolder?: pulumi.Input<boolean>;
    /**
     * Series type.
     */
    seriesType?: pulumi.Input<string>;
    /**
     * Should monitor.
     */
    shouldMonitor?: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Trakt additional parameters.
     */
    traktAdditionalParameters?: pulumi.Input<string>;
    /**
     * Trakt list type. '0' Trending, '1' Popular, '2' Anticipated, '3' TopWatchedByWeek, '4' TopWatchedByMonth, '5' TopWatchedByYear, '6' TopWatchedByAllTime, '7' RecommendedByWeek, '8' RecommendedByMonth, '9' RecommendedByYear, '10' RecommendedByAllTime.
     */
    traktListType?: pulumi.Input<number>;
    /**
     * Years.
     */
    years?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ImportListTraktPopular resource.
 */
export interface ImportListTraktPopularArgs {
    /**
     * Access token.
     */
    accessToken?: pulumi.Input<string>;
    /**
     * Auth User.
     */
    authUser?: pulumi.Input<string>;
    /**
     * Enable automatic add flag.
     */
    enableAutomaticAdd: pulumi.Input<boolean>;
    /**
     * Expires.
     */
    expires?: pulumi.Input<string>;
    /**
     * Genres.
     */
    genres?: pulumi.Input<string>;
    /**
     * Limit.
     */
    limit?: pulumi.Input<number>;
    /**
     * Import List name.
     */
    name: pulumi.Input<string>;
    /**
     * Quality profile ID.
     */
    qualityProfileId: pulumi.Input<number>;
    /**
     * Rating.
     */
    rating?: pulumi.Input<string>;
    /**
     * Refresh token.
     */
    refreshToken?: pulumi.Input<string>;
    /**
     * Root folder path.
     */
    rootFolderPath: pulumi.Input<string>;
    /**
     * Season folder flag.
     */
    seasonFolder: pulumi.Input<boolean>;
    /**
     * Series type.
     */
    seriesType: pulumi.Input<string>;
    /**
     * Should monitor.
     */
    shouldMonitor: pulumi.Input<string>;
    /**
     * List of associated tags.
     */
    tags?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Trakt additional parameters.
     */
    traktAdditionalParameters?: pulumi.Input<string>;
    /**
     * Trakt list type. '0' Trending, '1' Popular, '2' Anticipated, '3' TopWatchedByWeek, '4' TopWatchedByMonth, '5' TopWatchedByYear, '6' TopWatchedByAllTime, '7' RecommendedByWeek, '8' RecommendedByMonth, '9' RecommendedByYear, '10' RecommendedByAllTime.
     */
    traktListType: pulumi.Input<number>;
    /**
     * Years.
     */
    years?: pulumi.Input<string>;
}
