// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetImportListArgs, GetImportListResult, GetImportListOutputArgs } from "./getImportList";
export const getImportList: typeof import("./getImportList").getImportList = null as any;
export const getImportListOutput: typeof import("./getImportList").getImportListOutput = null as any;
utilities.lazyLoad(exports, ["getImportList","getImportListOutput"], () => require("./getImportList"));

export { GetImportListExclusionArgs, GetImportListExclusionResult, GetImportListExclusionOutputArgs } from "./getImportListExclusion";
export const getImportListExclusion: typeof import("./getImportListExclusion").getImportListExclusion = null as any;
export const getImportListExclusionOutput: typeof import("./getImportListExclusion").getImportListExclusionOutput = null as any;
utilities.lazyLoad(exports, ["getImportListExclusion","getImportListExclusionOutput"], () => require("./getImportListExclusion"));

export { GetImportListExclusionsResult } from "./getImportListExclusions";
export const getImportListExclusions: typeof import("./getImportListExclusions").getImportListExclusions = null as any;
utilities.lazyLoad(exports, ["getImportListExclusions"], () => require("./getImportListExclusions"));

export { GetImportListsResult } from "./getImportLists";
export const getImportLists: typeof import("./getImportLists").getImportLists = null as any;
utilities.lazyLoad(exports, ["getImportLists"], () => require("./getImportLists"));

export { ImportListArgs, ImportListState } from "./importList";
export type ImportList = import("./importList").ImportList;
export const ImportList: typeof import("./importList").ImportList = null as any;
utilities.lazyLoad(exports, ["ImportList"], () => require("./importList"));

export { ImportListCustomArgs, ImportListCustomState } from "./importListCustom";
export type ImportListCustom = import("./importListCustom").ImportListCustom;
export const ImportListCustom: typeof import("./importListCustom").ImportListCustom = null as any;
utilities.lazyLoad(exports, ["ImportListCustom"], () => require("./importListCustom"));

export { ImportListExclusionArgs, ImportListExclusionState } from "./importListExclusion";
export type ImportListExclusion = import("./importListExclusion").ImportListExclusion;
export const ImportListExclusion: typeof import("./importListExclusion").ImportListExclusion = null as any;
utilities.lazyLoad(exports, ["ImportListExclusion"], () => require("./importListExclusion"));

export { ImportListImdbArgs, ImportListImdbState } from "./importListImdb";
export type ImportListImdb = import("./importListImdb").ImportListImdb;
export const ImportListImdb: typeof import("./importListImdb").ImportListImdb = null as any;
utilities.lazyLoad(exports, ["ImportListImdb"], () => require("./importListImdb"));

export { ImportListPlexArgs, ImportListPlexState } from "./importListPlex";
export type ImportListPlex = import("./importListPlex").ImportListPlex;
export const ImportListPlex: typeof import("./importListPlex").ImportListPlex = null as any;
utilities.lazyLoad(exports, ["ImportListPlex"], () => require("./importListPlex"));

export { ImportListPlexRssArgs, ImportListPlexRssState } from "./importListPlexRss";
export type ImportListPlexRss = import("./importListPlexRss").ImportListPlexRss;
export const ImportListPlexRss: typeof import("./importListPlexRss").ImportListPlexRss = null as any;
utilities.lazyLoad(exports, ["ImportListPlexRss"], () => require("./importListPlexRss"));

export { ImportListSimklUserArgs, ImportListSimklUserState } from "./importListSimklUser";
export type ImportListSimklUser = import("./importListSimklUser").ImportListSimklUser;
export const ImportListSimklUser: typeof import("./importListSimklUser").ImportListSimklUser = null as any;
utilities.lazyLoad(exports, ["ImportListSimklUser"], () => require("./importListSimklUser"));

export { ImportListSonarrArgs, ImportListSonarrState } from "./importListSonarr";
export type ImportListSonarr = import("./importListSonarr").ImportListSonarr;
export const ImportListSonarr: typeof import("./importListSonarr").ImportListSonarr = null as any;
utilities.lazyLoad(exports, ["ImportListSonarr"], () => require("./importListSonarr"));

export { ImportListTraktListArgs, ImportListTraktListState } from "./importListTraktList";
export type ImportListTraktList = import("./importListTraktList").ImportListTraktList;
export const ImportListTraktList: typeof import("./importListTraktList").ImportListTraktList = null as any;
utilities.lazyLoad(exports, ["ImportListTraktList"], () => require("./importListTraktList"));

export { ImportListTraktPopularArgs, ImportListTraktPopularState } from "./importListTraktPopular";
export type ImportListTraktPopular = import("./importListTraktPopular").ImportListTraktPopular;
export const ImportListTraktPopular: typeof import("./importListTraktPopular").ImportListTraktPopular = null as any;
utilities.lazyLoad(exports, ["ImportListTraktPopular"], () => require("./importListTraktPopular"));

export { ImportListTraktUserArgs, ImportListTraktUserState } from "./importListTraktUser";
export type ImportListTraktUser = import("./importListTraktUser").ImportListTraktUser;
export const ImportListTraktUser: typeof import("./importListTraktUser").ImportListTraktUser = null as any;
utilities.lazyLoad(exports, ["ImportListTraktUser"], () => require("./importListTraktUser"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sonarr:ImportLists/importList:ImportList":
                return new ImportList(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListCustom:ImportListCustom":
                return new ImportListCustom(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListExclusion:ImportListExclusion":
                return new ImportListExclusion(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListImdb:ImportListImdb":
                return new ImportListImdb(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListPlex:ImportListPlex":
                return new ImportListPlex(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListPlexRss:ImportListPlexRss":
                return new ImportListPlexRss(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListSimklUser:ImportListSimklUser":
                return new ImportListSimklUser(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListSonarr:ImportListSonarr":
                return new ImportListSonarr(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListTraktList:ImportListTraktList":
                return new ImportListTraktList(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListTraktPopular:ImportListTraktPopular":
                return new ImportListTraktPopular(name, <any>undefined, { urn })
            case "sonarr:ImportLists/importListTraktUser:ImportListTraktUser":
                return new ImportListTraktUser(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importList", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListCustom", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListExclusion", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListImdb", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListPlex", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListPlexRss", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListSimklUser", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListSonarr", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListTraktList", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListTraktPopular", _module)
pulumi.runtime.registerResourceModule("sonarr", "ImportLists/importListTraktUser", _module)
