// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace DownloadClients {
    export interface GetDownloadClientsDownloadClient {
        /**
         * Add paused flag.
         */
        addPaused: boolean;
        /**
         * Add stopped flag.
         */
        addStopped: boolean;
        /**
         * Additional tags, `0` TitleSlug, `1` Quality, `2` Language, `3` ReleaseGroup, `4` Year, `5` Indexer, `6` Network.
         */
        additionalTags: number[];
        /**
         * API key.
         */
        apiKey: string;
        /**
         * Category.
         */
        category: string;
        /**
         * DownloadClient configuration template.
         */
        configContract: string;
        /**
         * Destination.
         */
        destination: string;
        /**
         * Enable flag.
         */
        enable: boolean;
        /**
         * Field tags.
         */
        fieldTags: string[];
        /**
         * First and last flag.
         */
        firstAndLast: boolean;
        /**
         * host.
         */
        host: string;
        /**
         * Download Client ID.
         */
        id: number;
        /**
         * DownloadClient implementation name.
         */
        implementation: string;
        /**
         * Initial state. `0` Start, `1` ForceStart, `2` Pause.
         */
        initialState: number;
        /**
         * Initial state, with Stop support. `0` Start, `1` ForceStart, `2` Pause, `3` Stop.
         */
        intialState: number;
        /**
         * Magnet file extension.
         */
        magnetFileExtension: string;
        /**
         * Download Client name.
         */
        name: string;
        /**
         * NZB folder.
         */
        nzbFolder: string;
        /**
         * Older TV priority. `0` Last, `1` First.
         */
        olderTvPriority: number;
        /**
         * Password.
         */
        password: string;
        /**
         * Port.
         */
        port: number;
        /**
         * Post import tags.
         */
        postImportTags: string[];
        /**
         * Priority.
         */
        priority: number;
        /**
         * Protocol. Valid values are 'usenet' and 'torrent'.
         */
        protocol: string;
        /**
         * Read only flag.
         */
        readOnly: boolean;
        /**
         * Recent TV priority. `0` Last, `1` First.
         */
        recentTvPriority: number;
        /**
         * Remove completed downloads flag.
         */
        removeCompletedDownloads: boolean;
        /**
         * Remove failed downloads flag.
         */
        removeFailedDownloads: boolean;
        /**
         * RPC path.
         */
        rpcPath: string;
        /**
         * Save magnet files flag.
         */
        saveMagnetFiles: boolean;
        /**
         * Secret token.
         */
        secretToken: string;
        /**
         * Sequential order flag.
         */
        sequentialOrder: boolean;
        /**
         * Start on add flag.
         */
        startOnAdd: boolean;
        /**
         * STRM folder.
         */
        strmFolder: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Torrent folder.
         */
        torrentFolder: string;
        /**
         * TV category.
         */
        tvCategory: string;
        /**
         * TV directory.
         */
        tvDirectory: string;
        /**
         * TV imported category.
         */
        tvImportedCategory: string;
        /**
         * Base URL.
         */
        urlBase: string;
        /**
         * Use SSL flag.
         */
        useSsl: boolean;
        /**
         * Username.
         */
        username: string;
        /**
         * Watch folder flag.
         */
        watchFolder: string;
    }

}

export namespace ImportLists {
    export interface GetImportListExclusionsImportListExclusion {
        /**
         * ImportListExclusion ID.
         */
        id: number;
        /**
         * Series to be excluded.
         */
        title: string;
        /**
         * Series TVDB ID.
         */
        tvdbId: number;
    }

    export interface GetImportListsImportList {
        /**
         * Access token.
         */
        accessToken: string;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * Auth User.
         */
        authUser: string;
        /**
         * Base URL.
         */
        baseUrl: string;
        /**
         * ImportList configuration template.
         */
        configContract: string;
        /**
         * Enable automatic add flag.
         */
        enableAutomaticAdd: boolean;
        /**
         * Expires.
         */
        expires: string;
        /**
         * Genres.
         */
        genres: string;
        /**
         * Import List ID.
         */
        id: number;
        /**
         * ImportList implementation name.
         */
        implementation: string;
        /**
         * Language profile IDs.
         */
        languageProfileIds: number[];
        /**
         * Limit.
         */
        limit: number;
        /**
         * List ID.
         */
        listId: string;
        /**
         * Simkl list type.
         */
        listType: number;
        /**
         * List name.
         */
        listname: string;
        /**
         * Import List name.
         */
        name: string;
        /**
         * Quality profile ID.
         */
        qualityProfileId: number;
        /**
         * Quality profile IDs.
         */
        qualityProfileIds: number[];
        /**
         * Rating.
         */
        rating: string;
        /**
         * Refresh token.
         */
        refreshToken: string;
        /**
         * Root folder path.
         */
        rootFolderPath: string;
        /**
         * Season folder flag.
         */
        seasonFolder: boolean;
        /**
         * Series type.
         */
        seriesType: string;
        /**
         * Should monitor.
         */
        shouldMonitor: string;
        /**
         * Tag IDs.
         */
        tagIds: number[];
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Trakt additional parameters.
         */
        traktAdditionalParameters: string;
        /**
         * Trakt list type.
         */
        traktListType: number;
        /**
         * URL.
         */
        url: string;
        /**
         * Username.
         */
        username: string;
        /**
         * Years.
         */
        years: string;
    }

}

export namespace Indexers {
    export interface GetIndexersIndexer {
        /**
         * Additional parameters.
         */
        additionalParameters: string;
        /**
         * Allow zero size files.
         */
        allowZeroSize: boolean;
        /**
         * Anime list.
         */
        animeCategories: number[];
        /**
         * Search anime in standard format.
         */
        animeStandardFormatSearch: boolean;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * API path.
         */
        apiPath: string;
        /**
         * Base URL.
         */
        baseUrl: string;
        /**
         * Captcha token.
         */
        captchaToken: string;
        /**
         * Series list.
         */
        categories: number[];
        /**
         * Indexer configuration template.
         */
        configContract: string;
        /**
         * Cookie.
         */
        cookie: string;
        /**
         * Delay before grabbing.
         */
        delay: number;
        /**
         * Download client ID.
         */
        downloadClientId: number;
        /**
         * Enable automatic search flag.
         */
        enableAutomaticSearch: boolean;
        /**
         * Enable interactive search flag.
         */
        enableInteractiveSearch: boolean;
        /**
         * Enable RSS flag.
         */
        enableRss: boolean;
        /**
         * Indexer ID.
         */
        id: number;
        /**
         * Indexer implementation name.
         */
        implementation: string;
        /**
         * Minimum seeders.
         */
        minimumSeeders: number;
        /**
         * Indexer name.
         */
        name: string;
        /**
         * Passkey.
         */
        passkey: string;
        /**
         * Priority.
         */
        priority: number;
        /**
         * Protocol. Valid values are 'usenet' and 'torrent'.
         */
        protocol: string;
        /**
         * Allow ranked only.
         */
        rankedOnly: boolean;
        /**
         * Season seed time.
         */
        seasonPackSeedTime: number;
        /**
         * Seed ratio.
         */
        seedRatio: number;
        /**
         * Seed time.
         */
        seedTime: number;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Username.
         */
        username: string;
    }

}

export namespace Languages {
    export interface GetLanguagesLanguage {
        /**
         * Language ID.
         */
        id: number;
        /**
         * Language.
         */
        name: string;
        /**
         * Language in lowercase.
         */
        nameLower: string;
    }

}

export namespace MediaManagement {
    export interface GetRootFolderUnmappedFolder {
        /**
         * Name of unmapped folder.
         */
        name: string;
        /**
         * Path of unmapped folder.
         */
        path: string;
    }

    export interface GetRootFoldersRootFolder {
        /**
         * Access flag.
         */
        accessible: boolean;
        /**
         * Root Folder ID.
         */
        id: number;
        /**
         * Root Folder absolute path.
         */
        path: string;
        /**
         * List of folders with no associated series.
         */
        unmappedFolders: outputs.MediaManagement.GetRootFoldersRootFolderUnmappedFolder[];
    }

    export interface GetRootFoldersRootFolderUnmappedFolder {
        name: string;
        path: string;
    }

    export interface RootFolderUnmappedFolder {
        /**
         * Name of unmapped folder.
         */
        name: string;
        /**
         * Path of unmapped folder.
         */
        path: string;
    }

}

export namespace Metadata {
    export interface GetMetadataConsumersMetadataConsumer {
        /**
         * Metadata configuration template.
         */
        configContract: string;
        /**
         * Enable flag.
         */
        enable: boolean;
        /**
         * Episode images flag.
         */
        episodeImages?: boolean;
        /**
         * Episode metadata flag.
         */
        episodeMetadata: boolean;
        /**
         * Metadata ID.
         */
        id: number;
        /**
         * Metadata implementation name.
         */
        implementation: string;
        /**
         * Metadata name.
         */
        name: string;
        /**
         * Season images flag.
         */
        seasonImages: boolean;
        /**
         * Series images flag.
         */
        seriesImages: boolean;
        /**
         * Series metadata flag.
         */
        seriesMetadata: boolean;
        /**
         * Series metadata URL flag.
         */
        seriesMetadataUrl: boolean;
        /**
         * List of associated tags.
         */
        tags: number[];
    }

}

export namespace Notifications {
    export interface GetNotificationsNotification {
        /**
         * Access token.
         */
        accessToken: string;
        /**
         * Access token secret.
         */
        accessTokenSecret: string;
        /**
         * Always update flag.
         */
        alwaysUpdate: boolean;
        /**
         * API key.
         */
        apiKey: string;
        /**
         * App token.
         */
        appToken: string;
        /**
         * Arguments.
         */
        arguments: string;
        /**
         * Password.
         */
        authPassword: string;
        /**
         * Auth token.
         */
        authToken: string;
        /**
         * Auth user.
         */
        authUser: string;
        /**
         * Username.
         */
        authUsername: string;
        /**
         * Author.
         */
        author: string;
        /**
         * Avatar.
         */
        avatar: string;
        /**
         * Bcc.
         */
        bccs: string[];
        /**
         * Bot token.
         */
        botToken: string;
        /**
         * Cc.
         */
        ccs: string[];
        /**
         * Channel.
         */
        channel: string;
        /**
         * Channel tags.
         */
        channelTags: string[];
        /**
         * Chat ID.
         */
        chatId: string;
        /**
         * Clean library flag.
         */
        cleanLibrary: boolean;
        /**
         * Click URL.
         */
        clickUrl: string;
        /**
         * Notification configuration template.
         */
        configContract: string;
        /**
         * Configuration key.
         */
        configurationKey: string;
        /**
         * Consumer key.
         */
        consumerKey: string;
        /**
         * Consumer secret.
         */
        consumerSecret: string;
        /**
         * Device IDs.
         */
        deviceIds: string[];
        /**
         * Device names.
         */
        deviceNames: string;
        /**
         * Devices.
         */
        devices: string[];
        /**
         * Direct message flag.
         */
        directMessage: boolean;
        /**
         * Display time.
         */
        displayTime: number;
        /**
         * Event.
         */
        event: string;
        /**
         * Expire.
         */
        expire: number;
        /**
         * Expires.
         */
        expires: string;
        /**
         * Tags and emojis.
         */
        fieldTags: string[];
        /**
         * From.
         */
        from: string;
        /**
         * Grab fields. `0` Overview, `1` Rating, `2` Genres, `3` Quality, `4` Group, `5` Size, `6` Links, `7` Release, `8` Poster, `9` Fanart.
         */
        grabFields: number[];
        /**
         * Host.
         */
        host: string;
        /**
         * Icon.
         */
        icon: string;
        /**
         * Notification ID.
         */
        id: number;
        /**
         * Notification implementation name.
         */
        implementation: string;
        /**
         * Import fields. `0` Overview, `1` Rating, `2` Genres, `3` Quality, `4` Codecs, `5` Group, `6` Size, `7` Languages, `8` Subtitles, `9` Links, `10` Release, `11` Poster, `12` Fanart.
         */
        importFields: number[];
        /**
         * Include health warnings.
         */
        includeHealthWarnings: boolean;
        /**
         * Key.
         */
        key: string;
        /**
         * Mention.
         */
        mention: string;
        /**
         * Method. `1` POST, `2` PUT.
         */
        method: number;
        /**
         * Notification name.
         */
        name: string;
        /**
         * Notification type. `0` Info, `1` Success, `2` Warning, `3` Failure.
         */
        notificationType: number;
        /**
         * Notify flag.
         */
        notify: boolean;
        /**
         * On application update flag.
         */
        onApplicationUpdate: boolean;
        /**
         * On download flag.
         */
        onDownload: boolean;
        /**
         * On episode file delete flag.
         */
        onEpisodeFileDelete: boolean;
        /**
         * On episode file delete for upgrade flag.
         */
        onEpisodeFileDeleteForUpgrade: boolean;
        /**
         * On grab flag.
         */
        onGrab: boolean;
        /**
         * On health issue flag.
         */
        onHealthIssue: boolean;
        /**
         * On health restored flag.
         */
        onHealthRestored: boolean;
        /**
         * On manual interaction required flag.
         */
        onManualInteractionRequired: boolean;
        /**
         * On rename flag.
         */
        onRename: boolean;
        /**
         * On series add flag.
         */
        onSeriesAdd: boolean;
        /**
         * On series delete flag.
         */
        onSeriesDelete: boolean;
        /**
         * On upgrade flag.
         */
        onUpgrade: boolean;
        /**
         * password.
         */
        password: string;
        /**
         * Path.
         */
        path: string;
        /**
         * Port.
         */
        port: number;
        /**
         * Priority.
         */
        priority: number;
        /**
         * Receiver ID.
         */
        receiverId: string;
        /**
         * Recipients.
         */
        recipients: string[];
        /**
         * Refresh token.
         */
        refreshToken: string;
        /**
         * Require encryption flag.
         */
        requireEncryption: boolean;
        /**
         * Retry.
         */
        retry: number;
        /**
         * Add silently flag.
         */
        sendSilently: boolean;
        /**
         * Sender domain.
         */
        senderDomain: string;
        /**
         * Sender ID.
         */
        senderId: string;
        /**
         * Sender Number.
         */
        senderNumber: string;
        /**
         * server.
         */
        server: string;
        /**
         * Server URL.
         */
        serverUrl: string;
        /**
         * Sign in.
         */
        signIn: string;
        /**
         * Sound.
         */
        sound: string;
        /**
         * Stateless URLs.
         */
        statelessUrls: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Token.
         */
        token: string;
        /**
         * Topics.
         */
        topics: string[];
        /**
         * To.
         */
        tos: string[];
        /**
         * Update library flag.
         */
        updateLibrary: boolean;
        /**
         * URL.
         */
        url: string;
        /**
         * Use EU endpoint flag.
         */
        useEuEndpoint: boolean;
        /**
         * Use SSL flag.
         */
        useSsl: boolean;
        /**
         * User key.
         */
        userKey: string;
        /**
         * Username.
         */
        username: string;
        /**
         * Web hook url.
         */
        webHookUrl: string;
    }

}

export namespace Profiles {
    export interface CustomFormatSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Max.
         */
        max: number;
        /**
         * Min.
         */
        min: number;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Required flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetCustomFormatSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Max.
         */
        max: number;
        /**
         * Min.
         */
        min: number;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Computed flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetCustomFormatsCustomFormat {
        /**
         * Custom Format ID.
         */
        id: number;
        /**
         * Include custom format when renaming flag.
         */
        includeCustomFormatWhenRenaming: boolean;
        /**
         * Custom Format name.
         */
        name: string;
        /**
         * Specifications.
         */
        specifications: outputs.Profiles.GetCustomFormatsCustomFormatSpecification[];
    }

    export interface GetCustomFormatsCustomFormatSpecification {
        implementation: string;
        max: number;
        min: number;
        name: string;
        negate: boolean;
        required: boolean;
        value: string;
    }

    export interface GetDelayProfilesDelayProfile {
        /**
         * Bypass for higher custom format score flag.
         */
        bypassIfAboveCustomFormatScore: boolean;
        /**
         * Bypass for highest quality Flag.
         */
        bypassIfHighestQuality: boolean;
        /**
         * Torrent allowed Flag.
         */
        enableTorrent: boolean;
        /**
         * Usenet allowed Flag.
         */
        enableUsenet: boolean;
        /**
         * Delay Profile ID.
         */
        id: number;
        /**
         * Minimum custom format score.
         */
        minimumCustomFormatScore: number;
        /**
         * Order.
         */
        order: number;
        /**
         * Preferred protocol.
         */
        preferredProtocol: string;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Torrent Delay.
         */
        torrentDelay: number;
        /**
         * Usenet delay.
         */
        usenetDelay: number;
    }

    export interface GetQualityDefinitionsQualityDefinition {
        /**
         * Quality Definition ID.
         */
        id: number;
        /**
         * Maximum size MB/min.
         */
        maxSize: number;
        /**
         * Minimum size MB/min.
         */
        minSize: number;
        /**
         * Quality ID.
         */
        qualityId: number;
        /**
         * Quality Name.
         */
        qualityName: string;
        /**
         * Quality Resolution.
         */
        resolution: number;
        /**
         * Quality source.
         */
        source: string;
        /**
         * Quality Definition Title.
         */
        title: string;
    }

    export interface GetQualityProfileFormatItem {
        /**
         * Format.
         */
        format: number;
        /**
         * Name.
         */
        name: string;
        /**
         * Score.
         */
        score: number;
    }

    export interface GetQualityProfileQualityGroup {
        /**
         * Quality group ID.
         */
        id: number;
        /**
         * Quality group name.
         */
        name: string;
        /**
         * Qualities in group.
         */
        qualities: outputs.Profiles.GetQualityProfileQualityGroupQuality[];
    }

    export interface GetQualityProfileQualityGroupQuality {
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Quality Profile Name.
         */
        name: string;
        resolution: number;
        source: string;
    }

    export interface GetQualityProfilesQualityProfile {
        /**
         * Quality ID to which cutoff.
         */
        cutoff: number;
        /**
         * Cutoff format score.
         */
        cutoffFormatScore: number;
        /**
         * Quality groups.
         */
        formatItems: outputs.Profiles.GetQualityProfilesQualityProfileFormatItem[];
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Min format score.
         */
        minFormatScore: number;
        /**
         * Quality Profile Name.
         */
        name: string;
        /**
         * Quality groups.
         */
        qualityGroups: outputs.Profiles.GetQualityProfilesQualityProfileQualityGroup[];
        /**
         * Upgrade allowed flag.
         */
        upgradeAllowed: boolean;
    }

    export interface GetQualityProfilesQualityProfileFormatItem {
        format: number;
        name: string;
        score: number;
    }

    export interface GetQualityProfilesQualityProfileQualityGroup {
        /**
         * The ID of this resource.
         */
        id: number;
        name: string;
        qualities: outputs.Profiles.GetQualityProfilesQualityProfileQualityGroupQuality[];
    }

    export interface GetQualityProfilesQualityProfileQualityGroupQuality {
        /**
         * The ID of this resource.
         */
        id: number;
        name: string;
        resolution: number;
        source: string;
    }

    export interface GetReleaseProfilesReleaseProfile {
        /**
         * Enabled
         */
        enabled: boolean;
        /**
         * Release Profile ID.
         */
        id: number;
        /**
         * Ignored terms.
         */
        ignoreds: string[];
        /**
         * Indexer ID. Set `0` for all.
         */
        indexerId: number;
        /**
         * Release profile name.
         */
        name: string;
        /**
         * Required terms.
         */
        requireds: string[];
        /**
         * List of associated tags.
         */
        tags: number[];
    }

    export interface QualityProfileFormatItem {
        /**
         * Format.
         */
        format: number;
        /**
         * Name.
         */
        name: string;
        /**
         * Score.
         */
        score: number;
    }

    export interface QualityProfileQualityGroup {
        /**
         * Quality group ID.
         */
        id: number;
        /**
         * Quality group name.
         */
        name: string;
        /**
         * Qualities in group.
         */
        qualities: outputs.Profiles.QualityProfileQualityGroupQuality[];
    }

    export interface QualityProfileQualityGroupQuality {
        /**
         * Quality Profile ID.
         */
        id: number;
        /**
         * Quality Profile Name.
         */
        name: string;
        resolution: number;
        source: string;
    }

}

export namespace Series {
    export interface GetAllSeriesSeries {
        /**
         * Series ID.
         */
        id: number;
        /**
         * Monitored flag.
         */
        monitored: boolean;
        /**
         * Series Path.
         */
        path: string;
        /**
         * Quality Profile ID.
         */
        qualityProfileId: number;
        /**
         * Series Root Folder.
         */
        rootFolderPath: string;
        /**
         * Season Folder flag.
         */
        seasonFolder: boolean;
        /**
         * List of associated tags.
         */
        tags: number[];
        /**
         * Series Title.
         */
        title: string;
        /**
         * Series Title in kebab format.
         */
        titleSlug: string;
        /**
         * TVDB ID.
         */
        tvdbId: number;
        /**
         * Scene numbering flag.
         */
        useSceneNumbering: boolean;
    }

}

export namespace Tags {
    export interface AutoTagSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Required flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetAutoTagSpecification {
        /**
         * Implementation.
         */
        implementation: string;
        /**
         * Specification name.
         */
        name: string;
        /**
         * Negate flag.
         */
        negate: boolean;
        /**
         * Computed flag.
         */
        required: boolean;
        /**
         * Value.
         */
        value: string;
    }

    export interface GetAutoTagsAutoTag {
        /**
         * Auto Tag ID.
         */
        id: number;
        /**
         * Auto Tag name.
         */
        name: string;
        /**
         * Remove tags automatically flag.
         */
        removeTagsAutomatically: boolean;
        /**
         * Specifications.
         */
        specifications: outputs.Tags.GetAutoTagsAutoTagSpecification[];
        /**
         * List of associated tags.
         */
        tags: number[];
    }

    export interface GetAutoTagsAutoTagSpecification {
        implementation: string;
        name: string;
        negate: boolean;
        required: boolean;
        value: string;
    }

    export interface GetRemotePathMappingsRemotePathMapping {
        /**
         * Download Client host.
         */
        host: string;
        /**
         * RemotePathMapping ID.
         */
        id: number;
        /**
         * Local path.
         */
        localPath: string;
        /**
         * Download Client remote path.
         */
        remotePath: string;
    }

    export interface GetTagsTag {
        /**
         * Tag ID.
         */
        id: number;
        /**
         * Tag label.
         */
        label: string;
    }

}
