// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * <!-- subcategory:Indexers -->Indexer Config.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarr from "@pulumi/sonarr";
 *
 * const example = sonarr.Indexers.getIndexerConfig({});
 * ```
 */
export function getIndexerConfig(opts?: pulumi.InvokeOptions): Promise<GetIndexerConfigResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarr:Indexers/getIndexerConfig:getIndexerConfig", {
    }, opts);
}

/**
 * A collection of values returned by getIndexerConfig.
 */
export interface GetIndexerConfigResult {
    /**
     * Delay Profile ID.
     */
    readonly id: number;
    /**
     * Maximum size.
     */
    readonly maximumSize: number;
    /**
     * Minimum age.
     */
    readonly minimumAge: number;
    /**
     * Retention.
     */
    readonly retention: number;
    /**
     * RSS sync interval.
     */
    readonly rssSyncInterval: number;
}
